name: Site Release
on:
  push:
    tags:
      - "v*"
jobs:
  site-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Yarn
        working-directory: ./web
        run:
          npm install --global yarn
      - name: Install dependencies
        working-directory: ./web
        run:
          yarn
      - name: Web Prod Build
        working-directory: ./web
        run:
          yarn build
      # https://github.com/marketplace/actions/add-commit
      - uses: EndBug/add-and-commit@v9
        with:
          add: '.'
          author_name: GH Action
          committer_name: GH Action
          message: 'Release ${{ env.GITHUB_REF_NAME }}'
          push: true

